### ISSUE TITLE
Cannot find item "vm.memory.size[webui,total]" on "Asus Router by Zabbix Agent" used as the Y axis MAX value for graph "Memory WEBUI".

### ISSUE THREAD

**Issue by DRN88** [diasdmhub/Zabbix_Template_Asus_Merlin#3] opened 2021-09-07 10:26 UTC
I get this error when trying to import `AsusRouter_template_v9.yaml` into Zabbix server 5.4.4

```
Cannot find item "vm.memory.size[webui,total]" on "Asus Router by Zabbix Agent" used as the Y axis MAX value for graph "Memory WEBUI".
```

The fix is (please verify): Replace all occurrence of `vm.memory.size[webui,total]` to `vm.memory.size[total]`

Thanks for the template.

**Comment by diasdmhub** [comment] 2021-09-07 14:45
"_Memory WEBUI_" graph references "_Memory WebUI Total_" item in "_Y axis MAX value_" configuration.

"_Memory WebUI Total_" item uses key `vm.memory.size[webui,total]` and is dependent on "_Total memory_" item (`vm.memory.size[total]`).

The key "`vm.memory.size[total]`" comes from "_Linux memory by Zabbix agent_" template.
Therefore, "_Linux memory by Zabbix agent_" template is required and `vm.memory.size[webui,total]` key should not be replaced from "_Memory WEBUI_" graph.

Please, check if your server has "_Linux memory by Zabbix agent_" and "_Linux memory by Zabbix agent active_" [OOTB templates](https://www.zabbix.com/documentation/current/manual/config/templates_out_of_the_box).

**Comment by diasdmhub** [comment] 2021-09-07 15:35
After some testing, I realised the issue is "_Memory WebUI Total_" item was not added to the _.yaml_ file.
I'll be looking into it.

**Comment by diasdmhub** [comment] 2021-09-07 21:08
I've uploaded a new file for "revision" branch.
Please try to download "[AsusRouter_template_v9.1.yaml](https://github.com/diasdmhub/Zabbix_Template_Asus_Merlin/blob/Revision/Template/AsusRouter_template_v9.1.yaml)" file instead and report back if you can.

**Comment by diasdmhub** [comment] 2021-09-13 13:46
I haven't found any more issues after changing "Memory WebUI Total" item calculation.
Therefore, I merged the revision to the main branch and it is now in production.

If you find any other issue, please, report back.
Thank you.

**Closed by diasdmhub** 2021-09-13 13:46 UTC
Labels: bug

**Comment by DRN88** [comment] 2021-09-14 20:23
Confirmed working. Cheers!
